server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongdb:
      uri: mongodb://localhost:27017/learnify

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/